{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyP53dSef2e0OiCU8vwxnVfW"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["#### 에러(Error) vs. 예외(Exception).\n","\n","에러(Error):\n","- 에러는 주로 프로그램 실행 전에 발생하는, 프로그램의 잘못된 구문이나 절차 등에 의해 발생하는 문제를 말한다.\n","- 대표적인 에러로는 구문 에러(SyntaxError)가 있다. 예를 들어, 올바르지 않은 들여쓰기나 잘못된 코드 구조로 인해 파이썬 인터프리터가 코드를 실행하기 전에 에러를 발생시킨다.\n","- 에러는 대체로 프로그램의 수정 없이는 복구될 수 없는 심각한 문제들이다.\n","\n","예외(Exception):\n","- 예외는 실행 중인 프로그램에 영향을 주는 이벤트로, 일반적인 프로그램 흐름을 방해한다.\n","- 예외는 프로그램의 정상적인 흐름을 방해하지만, 적절한 예외 처리를 통해 프로그램의 중단 없이 예외를 '잡아내고(catch)' 처리할 수 있다. 예를 들어, 파일을 열 때 파일이 존재하지 않는 경우 FileNotFoundError 예외가 발생할 수 있다. 이 경우 적절한 except 블록으로 예외를 처리하여 사용자에게 메시지를 표시하고 대안적인 행동을 취할 수 있다.\n","- 예외는 try-except 블록을 통해 프로그램에서 처리할 수 있으며, 이를 통해 프로그램이 예외 상황에서도 안정적으로 동작하도록 만들 수 있다.\n","\n","요약하자면, 에러는 대개 코드 수정이 필요한 문제들을 가리키며, 예외는 프로그램 실행 중에 발생하지만 적절히 처리할 수 있는 예상 가능한 '예외적' 상황들을 말한다.\n","\n","#### 파이썬에서 발생할 수 있는 에러와 예외의 유형:\n","에러 : 프로그램이 실행되기 전에 발생하는 문제\n","- SyntaxError: 코드의 구문이 잘못되었을 때 생긴다.<br>\n","\n","예외 : 실행 시간(runtime) 중에 발생하고 처리 가능\n","- NameError: 정의되지 않은 변수를 호출할 때 생긴다.\n","- TypeError: 연산이나 함수가 부적절한 유형의 객체에 적용될 때 발생한다.\n","- ValueError: 연산이나 함수가 적절하지 않은 값을 객체에 적용할 때 발생한다.\n","- IndexError: 리스트 등의 시퀀스에서 존재하지 않는 인덱스를 사용할 때 생긴다.\n","- KeyError: 딕셔너리에서 존재하지 않는 키를 사용할 때 발생한다.\n","- AttributeError: 존재하지 않는 속성이나 메서드를 호출할 때 생긴다.\n","- IOError 또는 OSError: 파일 입출력 과정에서 에러가 생길 때 발생한다.\n","- ZeroDivisionError: 0으로 나눌 때 생긴다.\n","- ImportError: 모듈을 임포트할 수 없을 때 발생한다.\n","- StopIteration: 이터레이터에 더 이상의 아이템이 없을 때 next()를 호출하면 발생한다.\n","- MemoryError: 메모리 할당이 실패할 때 생긴다.\n","- RecursionError: 재귀 호출이 너무 깊어질 때 발생한다."],"metadata":{"id":"T3GufSkRE5Lk"}},{"cell_type":"code","execution_count":2,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"9-CPwwpVEo_-","executionInfo":{"status":"ok","timestamp":1715237360670,"user_tz":-540,"elapsed":16,"user":{"displayName":"윤경","userId":"08475145638068530881"}},"outputId":"a3a609e1-3412-4b59-e0a3-453b18438fda"},"outputs":[{"output_type":"stream","name":"stdout","text":["예외를 강제로 발생\n"]}],"source":["# 구문 오류 : 프로그램 실행 전에 발생하는 오류\n","# 예외 또는 런타임 오류 : 프로그램 실행중에 발생하는 오류\n","\n","# print(\"예외를 강제로 발생)\n","print(\"예외를 강제로 발생\")"]},{"cell_type":"code","source":["# SyntaxError: 잘못된 구문\n","for i in range(10) # :이 없음\n","    print(i)"],"metadata":{"id":"jeTzxoIFHAOo"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# NameError : 정의되지 않은 변수 사용\n","print(unknown_var) # unknown_var 변수의 값을 만들지 않음"],"metadata":{"id":"rpIKxl3XHNr1"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":[],"metadata":{"id":"BquCQKUcHg4i"},"execution_count":null,"outputs":[]}]}